---
kind: pipeline
name: default

steps:
- name: trigger  
  image: plugins/downstream
  settings:
    server:
      from_secret: drone_server
    token:
      from_secret: drone_token
    repositories:
      from_secret: int_repo
  params:
      - TESTER=qwerty
  when:
      event:
        - tag
        - push

- name: after
  image: alpine
  commands:
  - echo "After build"
