---
kind: pipeline
name: default

steps:
- name: trigger  
  image: plugins/downstream
  settings:
    server:
      from_secret: drone_server
    token:
      from_secret: drone_token
    fork: true
    wait: true
    repositories:
      from_secret: int_repo

- name: after
  image: alpine
  commands:
  - echo "After build"
