---
kind: pipeline
name: default

steps:
- name: trigger  
  image: plugins/downstream
  settings:
    server: https://drone-dev.scalr-labs.net/
    token:
      from_secret: drone_token
    fork: true
    repositories:
      - vmotso-test-org/int-hello-world
