name: Default

on: [push, pull_request]

jobs:
  base:
    name: Base checks and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fmt
        uses: actions/setup-go@v2
        with:
          go-version: "1.11.4"
        run: test -z $(gofmt -l .)

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v2.2.0

      # - name: Unit tests
      #   run: make test
