name: Default

on: [push, pull_request]

jobs:
  base:
    name: Base checks and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.11.4
        uses: actions/setup-go@v2
        with:
          go-version: "1.11.4"

      - name: Code formatting
        run: test -z $(gofmt -l .)

      - name: Built-in analyzers
        run: go vet

      # - name: Unit tests
      #   run: make test
